language: python
python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "3.5"
install:
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda config --add channels ericmjl

  # Useful for debugging any issues with conda
  - conda info -a

  # Install Python, py.test, and required packages.
  - conda env create -f build-env.yml
  - source activate build
  - python setup.py install

script:
  # Your test script goes here
  - pycodestyle .
  - py.test

after_success:
  - bash <(curl -s https://codecov.io/bash)
